#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Scope-Guard
Version  : 0.21
Release  : 2
URL      : http://search.cpan.org/CPAN/authors/id/C/CH/CHOCOLATE/Scope-Guard-0.21.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/C/CH/CHOCOLATE/Scope-Guard-0.21.tar.gz
Summary  : 'lexically-scoped resource management'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Scope-Guard-doc

%description
Scope-Guard version 0.21
========================
This module provides a convenient way to perform cleanup or other forms of resource
management at the end of a scope. It is particularly useful when dealing with exceptions:
the Scope::Guard constructor takes a reference to a subroutine that is guaranteed to
be called even if the thread of execution is aborted prematurely. This effectively allows
lexically-scoped "promises" to be made that are automatically honoured by perl's garbage
collector.

%package doc
Summary: doc components for the perl-Scope-Guard package.
Group: Documentation

%description doc
doc components for the perl-Scope-Guard package.


%prep
%setup -q -n Scope-Guard-0.21

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Scope/Guard.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
